<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
  <xacro:include filename="common_inertial.xacro" />
  <xacro:macro name="base_xacro" params="length radius">
    <link name="base_footprint" />

    <!-- 机器人身体部分 -->
    <link name="base_link">
      <!--部件外观描述-->
      <visual>
        <!--沿着自己几何中心的偏移和旋转-->
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <!--几何形状-->
        <geometry>
          <!--圆柱体 radius 半径 0.10m 高度 length 0.12m-->
          <cylinder radius="${radius}" length="${length}"/>
        </geometry>
        <!--材质-->
        <material name="white">
          <color rgba="1.0 1.0 1.0 0.5"/>  
        </material>
      </visual>

      <collision>
        <!--沿着自己几何中心的偏移和旋转-->
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <!--几何形状-->
        <geometry>
          <!--圆柱体 radius 半径 0.10m 高度 length 0.12m-->
          <cylinder radius="${radius}" length="${length}"/>
        </geometry>
        <!--材质-->
        <material name="white">
          <color rgba="1.0 1.0 1.0 0.5"/>  
        </material>
      </collision>

      <xacro:cylinder_inertia m="1.0" r="${radius}" h="${length}" />

    </link>

    <joint name="joint_name" type="fixed">
      <!--关节连接的部件-->
      <parent link="base_footprint"/>
      <child link="base_link"/>
      <!--关节的偏移和旋转-->
      <origin xyz="0 0 ${length/2.0+0.032-0.001}" rpy="0 0 0"/>
    </joint>

  </xacro:macro>


</robot> 